name: AWS CI/CD Destroy

on:
  workflow_dispatch: # Allows manual triggering of the workflow

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # ================= AWS =================
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::950992723716:role/github-actions-role
          aws-region: us-east-1

      # ================= Terraform =================
      - name: Terraform Init
        run: |
          cd accounts/dev
          terraform init

      - name: Terraform Destroy
        run: |
          cd accounts/dev
          terraform destroy -auto-approve